---
title: "Useful Commands in R"
author: "Himansu Sahoo"
First draft date: "October 20, 2015"
Recent modified : "April 27, 2016"
output: html_document
---

Below are a quick summary of commands for data analysis in R.

### Basic commands about the library and getting dataset
```{r}
#.libPaths() # installed R library path
#library() # list all available packages in the library
#search()
#ls(); objects() # list of objects in the environment
#getwd(); setwd("/Users/dir/") # set working directory
#dir() # list of files in the working directory
#library(datasets); data(), data(iris) # list of datasets in datasets package
#search()
#source("file.R") # run a R code
#data(package = .packages(all.available = TRUE)) # list of datasets in all available packages
#data() # list of datasets in all packages
#data(package="dplyr") # list of datasets in the package dplyr
#alt+Apple+L  # to clear the screen
#args(sd) # shows the arguments for the function
#?sd() or help(sd) # for help for the function
```

### Installing packages
```{r}
#"packagename" %in% rownames(installed.packages()) # to check if a package is installed or not
#packageDescription("caret")
packageDescription("caret")[["Version"]]
library("caret") # require("caret") # call a library
#installed.packages()
#update.packages()
packageVersion("caret")
#install.packages("packagename")
#update.packages("packagename")
```

### Commands to explore a dataset

```{r}
#library(iris); attach(iris) # loads the library in the search path
# data(iris)
#class(dataset) # output is data.frame
#dim(dataset); nrow(dataset); ncol(dataset)
#dim(dataset)[1] # number of rows
#dim(dataset)[2] # number of columns
#print(dataset) # print all the data, don't do this, it will print everything
#head(dataset) # print first 6 rows
#head(dataset, n=100) # print first 100 rows
#tail(dataset) # print last 6 rows
#tail(dataset, n=100) # print last 100 rows
```


```{r}
#names(dataset); colnames(dataset) # print column names or variable names
#str(dataset) # class of each variable
#summary(dataset) # five number summary of each variable, will shows NA's, empty values
#colSums(is.na(dataset)) # number of missing values for each variable
# data_new <- na.omit(dataset) # remove all missing values
```

### Commands to explore a numeric variable
```{r}
#class(var)
#length(var)
#str(var)
#summary(var) # five number summary, will show how many NA's
#sort(var) # sort a vector
#var[!is.na(var)]; na.omit(var) # remove NA's from a vector
#sum(is.na(var)) # how many NA's in a vector
#as.factor(var_numeric) # change a numeric variable to a factor variable
```

### Statistics about a numeric variable
```{r}
#mean(var, na.rm=TRUE) # calculate mean, the default value na.rm=FALSE
# = sum(var)/length(var)
#meadian(var, na.rm=TRUE) # calculate median
#min(var), max(var), range(var) # minimum, maximum, range of avector
#IQR(var, na.rom=TRUE) # inter quartile range
#summary(var) # five number summary
#var(variable) # variance of a variable (average/mean of the squarded differences from the mean)
#sd(var) # standard deviation (sqrt(var(variable)))
```

### Commands to explore a categorical variable
```{r}
#class(var)
#length(var)
#str(var)
#summary(var) # five number summary, will show how many NA's
#table(var)
#prop.table(table(var))
```



### Git and Github related
```
First clone a github repository to the local computer.
git clone https://github.com/himansu979/Rsummary.git
cd Rsummary/
git status
git add --all
git status
git commit -m "adding new file"
git status
git push
```









